name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.6.3
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: test
      run: mvn test --file pom.xml 
    - name: build
      run: mvn package --file pom.xml -DskipTests
